### ISSUE TITLE
Windows: Install MIGW dependency for x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by georgik** [esp-rs/espup#10]
Install MIGW dependency for x86_64-pc-windows-gnu.

Without this dependency, the user will get an error during builds like

### How to simulate

Run the following command in Windows Sandbox:

```
 .\espup.exe install
```

### Solution

Implemented here: https://github.com/espressif/idf-env/blob/main/src/rust.rs#L484

Consider pointing directly to mingw repo, instead of esp-rs zipped version. The crate sevenz-rust for unpacking 7zip was improved and contains support also for unpacking Windows binaries: https://github.com/dyz1990/sevenz-rust/issues/1

The new version of sevenz-rust should make it possible to remove this workaround: https://github.com/espressif/idf-env/blob/main/src/rust.rs#L182

This command should be deployed before any `cargo install` takes place.

**Comment by SergioGasquez** [comment]
As a summary for those who are not familiar with this issue (or #9) or with Rust in Windows, there are two ABIs available for Windows:
- MSVC: Is the recommended one, and when installing `rustup` on Windows, it will [check if all the requirements are met](https://github.com/rust-lang/rustup/blob/cf29f82a3dac22960ae1d0aeebfe4ebb0c508783/src/cli/self_update/windows.rs#L91-L120). If those requirements are not installed, it [allows the user to install them.](https://github.com/rust-lang/rustup/blob/cf29f82a3dac22960ae1d0aeebfe4ebb0c508783/src/cli/self_update/windows.rs#L163-L247). 
  - Here is the PR that added those checks: https://github.com/rust-lang/rustup/pull/2954
- GNU: No checks are done in `rustup` and expect that the user takes care of properly installing it. 

#9 and #10 are the result of not having any of the proper ABI installed, and therefore, not meeting the [Compile-time Requirements](https://github.com/rust-lang/cc-rs#compile-time-requirements).

At the moment, in `espup`, we are [checking if `rustup` is installed, and if is not, we install it](https://github.com/esp-rs/espup/blob/main/src/toolchain/rust_toolchain.rs#L197-L222), but we do check if the ABI is installed. With #9 and #10 we would add an argument to `espup` so that users can install the desired ABI. 

So, I see two ways of dealing with this:
- Add rustup as a requirement for `espup`:
  - We would document it as a requirement and add the proper resources so users can install it, although, I would assume that most of the users that get to `espup` already have `rustup` installed.
  - In the code, we should still check if `rustup` is installed, but this time, if we do not find it we should just bail and tell the user to install it.
  - We could also open an issue in `rustup` to try to get  GNU ABI to behave like MSVC, where `rustup` could detect if installed and allow installing it if is not installed.
 - Allowing the user to install the ABIs from `espup`:
   - Which is basically whats is done in `idf-env` ([MinGW installation](https://github.com/espressif/idf-env/blob/main/src/rust.rs#L269-L284), and [MSVC installation](https://github.com/espressif/idf-env/blob/main/src/rust.rs#L335-L365)).
   - The issue that I see with this approach is that there are many valid combinations depending on Windows version/MSVC version/GNU version... 
     - As an example, in `idf-env` we are installing [`Microsoft.VisualStudio.Component.Windows10SDK.20348`](https://github.com/espressif/idf-env/blob/main/src/rust.rs#L353) and `rustup` installs  [`Microsoft.VisualStudio.Component.Windows11SDK.22000`](https://github.com/rust-lang/rustup/blob/cf29f82a3dac22960ae1d0aeebfe4ebb0c508783/src/cli/self_update/windows.rs#L205). 
     - For MSVC would basically mean "copying" what's done in `rustup` and keeping it up to date (which is what may cause some troubles)
     - For GNU it would mean implementing the installation of MinGW from `idf-env`
     
I would go for the option where we add `rustup` as a requirement since it avoids duplicating some logic from `rustup` and avoids the burden of having to keep the ABIs requirements up to date. This option would be even better if `rustup` added some checks for GNU requirements and the option to install them. 

Please, let me know your opinion or if I am missing something.

Any other opinion/option is also more than welcome! @georgik @jessebraham @bjoernQ @MabezDev @JurajSadel

**Comment by bjoernQ** [comment]
I'd say option one (rustup as a requirement) is a very good option. As you said most users will already have it. Also, I'd say that if someone is willing to use GNU ABI those users are already used to the pain 😄

**Comment by jessebraham** [comment]
@SergioGasquez and I discussed this yesterday and I also am of the opinion that the first option is the better one.

**Comment by georgik** [comment]
rustup deployment is integral part of vanilla boostrap environment. Please add the bootstrapping mechanism back.

**Comment by georgik** [comment]
Thank you @SergioGasquez for returning the feature back.
Windows will be resolved the next week, we might be able to leverage `winget` tool which can treat VC Tools, MSYS2 and other stuff like pre-requisities and can reduce amount of code that we need to write.

**Comment by SergioGasquez** [comment]
As discussed in #154, `espup` won't install this dependency.
