### ISSUE TITLE
rust-analyzer support

### ISSUE THREAD

**Issue by oleid** [esp-rs/espup#254]
## Motivations

When I set up an `esp32` toolchain via `espup` and use the cargo template, I end up with non-working `rust-ananlyzer`:

``` 
error: 'rust-analyzer' is not installed for the toolchain 'esp'
note: this is a custom toolchain, which cannot use `rustup component add`
help: if you built this toolchain from source, and used `rustup toolchain link`, then you may be able to build the component with `x.py`
```

One can work-around this by manually linking `rust-analyzer` from a different toolchain to the binary folder of `esp`, yet this will only partially work, since `rust-ananlyzer` won't be able to load `.so` files of the proc-macros.

![image](https://github.com/esp-rs/espup/assets/3369899/15ca4ee5-268e-4fc5-8570-28bcfc8d00c8)

## Solution

It would be best to provide `rust-analyzer` directly via espup.

## Alternative

For convenience, one could auto-link `rust-analyzer` to the binary of the current default toolchain.

**Comment by SergioGasquez** [comment]
Do you have any suggestion on how we could solve this in `espup`? `espup` basically, downloads the artifacts generated in https://github.com/esp-rs/rust-build

**Comment by Angr1st** [comment]
I think what would be needed, is the rust-analyzer-proc-macro-srv. The code for it should be inside the rust fork for esp.

**Comment by SergioGasquez** [comment]
We've had similar issues in the past, see https://github.com/esp-rs/esp-template/issues/58, but I dont think we cant do much from the esp-rs organization.

**Comment by Angr1st** [comment]
I think the description of this issue is misleading. Rust-analyzer works except for the proc macro expansion but you are right this is nothing that cant be fixed in espup. There are two ways I think this can be 'solved':
1. Just disable proc macro expansion ( "rust-analyzer.procMacro.enable": false )
2. Fix the unsupported ABI issue in esps rust fork

**Comment by SergioGasquez** [comment]
I'll close this issue as I don't think we can do anything else on our side and the issue does not really belongs here. Same applies to https://github.com/esp-rs/esp-template/issues/58, https://github.com/esp-rs/esp-idf-template/issues/74 and https://github.com/esp-rs/esp-template/issues/90

**Comment by lo-co** [comment]
I know this is a closed, but how come this is not mentioned in the documentation?

**Comment by KingRocco21** [comment]
I'm disappointed that this rust-analyzer issue was closed without being fully solved or documented.
Although Zed does come with rust-analyzer in case issues like these arise, both their stable and pre-release versions can occasionally fail due to being out of date.

Anyways, symlinking stable rust-analyzer was not enough to solve this issue for me. I also had to set the environment variable `RUSTUP_TOOLCHAIN` to "stable". I'm guessing this is because rust-analyzer tries to use the "esp" toolchain that is specified in my `rust-toolchain.toml`, but doesn't accept the symlink for whatever reason.

I am adding this here in case other nix-shell users struggle to use nixpkgs's or rustup's rust-analyzer in combination with espup.
